package com.saulhdev.feeder

import com.saulhdev.feeder.data.db.models.Feed
import com.saulhdev.feeder.viewmodels.Narrowing
import com.saulhdev.feeder.viewmodels.SourceListState
import com.saulhdev.feeder.viewmodels.SourceSort
import com.saulhdev.feeder.viewmodels.rangeBetween
import com.saulhdev.feeder.viewmodels.groupByTag
import com.saulhdev.feeder.viewmodels.matches
import com.saulhdev.feeder.viewmodels.survivingCategory
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.net.URL
import kotlin.time.Instant

private fun feed(
    id: Long = 1,
    title: String = "",
    url: String = "https://example.com/feed",
    tag: String = "",
    lastSync: Long = 0,
) = Feed(
    id = id,
    title = title,
    url = URL(url),
    tag = tag,
    lastSync = Instant.fromEpochMilliseconds(lastSync),
)

class SourceListTest {

    @Test
    fun `an empty query matches everything`() {
        assertTrue(feed(title = "The Guardian").matches(""))
        assertTrue(feed(title = "The Guardian").matches("   "))
    }

    @Test
    fun `search finds a source by name, address or category`() {
        val f = feed(title = "The Guardian", url = "https://theguardian.com/europe/rss", tag = "News,World")
        assertTrue("by name", f.matches("guardian"))
        assertTrue("by address", f.matches("europe"))
        assertTrue("by category", f.matches("world"))
        assertFalse(f.matches("cricket"))
    }

    @Test
    fun `search ignores case and surrounding space`() {
        val f = feed(title = "Ars Technica")
        assertTrue(f.matches("ARS"))
        assertTrue(f.matches("  ars  "))
    }

    @Test
    fun `sorting by name is case-insensitive`() {
        val feeds = listOf(feed(title = "zdnet"), feed(title = "Ars"), feed(title = "BBC"))
        val sorted = feeds.sortedWith(SourceSort.Title.comparator(emptyMap())).map(Feed::title)
        assertEquals(listOf("Ars", "BBC", "zdnet"), sorted)
    }

    @Test
    fun `sorting by category uses the first of several, not the raw string`() {
        val feeds = listOf(
            feed(title = "b", tag = "World,Alpha"),
            feed(title = "a", tag = "Tech"),
        )
        val sorted = feeds.sortedWith(SourceSort.Category.comparator(emptyMap())).map(Feed::title)
        assertEquals(listOf("a", "b"), sorted)
    }

    @Test
    fun `added reads insertion order off the autogenerated id`() {
        // Ascending, like every comparator here — the view model reverses it
        // when the reader asks for the other direction, so the enum must not
        // bake a direction into itself. "Recently added" used to, which left
        // no way to ask for oldest first and made the menu look like it
        // offered four orders when it offered two and a half.
        val feeds = listOf(
            feed(id = 1, title = "first"),
            feed(id = 7, title = "newest"),
            feed(id = 4, title = "middle"),
        )
        val sorted = feeds.sortedWith(SourceSort.Added.comparator(emptyMap())).map(Feed::title)
        assertEquals(listOf("first", "middle", "newest"), sorted)
    }

    @Test
    fun `every order reverses cleanly`() {
        // What tapping the chosen row does. Worth a test because it is the
        // only way to reach half the orders the menu now offers.
        // Every field distinct, deliberately. A stable sort does not reverse
        // tied elements and should not, so a fixture where all three share a
        // category would be testing Kotlin's sort rather than these
        // comparators.
        val feeds = listOf(
            feed(id = 1, title = "Ars", tag = "Tech"),
            feed(id = 2, title = "zdnet", tag = "World"),
            feed(id = 3, title = "BBC", tag = "News"),
        )
        val latest = mapOf(1L to 300L, 2L to 100L, 3L to 200L)
        SourceSort.entries.forEach { option ->
            val up = feeds.sortedWith(option.comparator(latest)).map(Feed::title)
            val down = feeds.sortedWith(option.comparator(latest).reversed()).map(Feed::title)
            assertEquals(option.name, up, down.reversed())
        }
    }

    @Test
    fun `latest post sorts the quietest feed first`() {
        // The useful end of this order: a feed that has published nothing for
        // months is the one worth looking at.
        val feeds = listOf(
            feed(id = 1, title = "busy"),
            feed(id = 2, title = "quiet"),
            feed(id = 3, title = "middling"),
        )
        val latest = mapOf(1L to 9_000L, 2L to 1_000L, 3L to 5_000L)
        val sorted = feeds.sortedWith(SourceSort.LatestPost.comparator(latest)).map(Feed::title)
        assertEquals(listOf("quiet", "middling", "busy"), sorted)
    }

    @Test
    fun `a feed with no articles at all sorts before every other`() {
        // It is the quietest of the lot, and usually broken, so the top of an
        // ascending list is exactly where it belongs. It must not be dropped
        // or throw for having no entry in the map.
        val feeds = listOf(feed(id = 1, title = "has posts"), feed(id = 2, title = "empty"))
        val latest = mapOf(1L to 5_000L)
        val sorted = feeds.sortedWith(SourceSort.LatestPost.comparator(latest)).map(Feed::title)
        assertEquals(listOf("empty", "has posts"), sorted)
    }

    @Test
    fun `latest post is not last sync`() {
        // The order this replaced sorted on Feeds.lastSync, which records when
        // Whisper last fetched a feed rather than when the feed last published
        // — so a feed checked every hour that has published nothing since
        // March had the most recent value in the list. Nothing here reads
        // lastSync, and this test exists to keep it that way.
        val busyFetchQuietFeed = feed(id = 1, title = "quiet", lastSync = 9_999L)
        val rarelyFetchedLivelyFeed = feed(id = 2, title = "lively", lastSync = 1L)
        val latest = mapOf(1L to 100L, 2L to 8_000L)
        val sorted = listOf(busyFetchQuietFeed, rarelyFetchedLivelyFeed)
            .sortedWith(SourceSort.LatestPost.comparator(latest)).map(Feed::title)
        assertEquals(listOf("quiet", "lively"), sorted)
    }

    @Test
    fun `four orders, and none of them names a direction`() {
        assertEquals(4, SourceSort.entries.size)
    }

    @Test
    fun `every sort option carries a label`() {
        SourceSort.entries.forEach { assertTrue(it.name, it.labelId != 0) }
    }

    @Test
    fun `a stored order resolves by name`() {
        assertEquals(SourceSort.Category, SourceSort.byName("Category"))
        assertEquals(SourceSort.Added, SourceSort.byName("Added"))
    }

    @Test
    fun `an order that no longer exists falls back rather than throwing`() {
        // "LastSync" was a real option and is not any more, so it is sitting in
        // the DataStore of every phone that used it. Resolving by ordinal
        // would have silently repointed those at whatever now occupies that
        // position; resolving by name gives nothing, and nothing means Title.
        assertEquals(SourceSort.Title, SourceSort.byName("LastSync"))
        assertEquals(SourceSort.Title, SourceSort.byName(null))
        assertEquals(SourceSort.Title, SourceSort.byName(""))
    }

    @Test
    fun `grouping by tag puts a multi-category source in every one of them`() {
        val feeds = listOf(
            feed(id = 1, title = "both", tag = "News,Tech"),
            feed(id = 2, title = "tech", tag = "Tech"),
        )
        val map = groupByTag(feeds, listOf("News", "Tech"))
        assertEquals(listOf("both"), map["News"]?.map(Feed::title))
        assertEquals(listOf("both", "tech"), map["Tech"]?.map(Feed::title))
    }

    @Test
    fun `a category is not matched by a prefix of another`() {
        // "New" used to match a source tagged "News", because the tag was one
        // comma-separated string and the check was contains().
        val map = groupByTag(listOf(feed(title = "n", tag = "News")), listOf("New", "News"))
        assertEquals(emptyList<String>(), map["New"]?.map(Feed::title))
        assertEquals(listOf("n"), map["News"]?.map(Feed::title))
    }

    @Test
    fun `the untagged bucket holds only the untagged`() {
        // It once matched every source, so an OPML export wrote each feed
        // twice: once under its category and once under none.
        val feeds = listOf(
            feed(id = 1, title = "filed", tag = "News"),
            feed(id = 2, title = "loose", tag = ""),
        )
        val map = groupByTag(feeds, listOf("News"))
        assertEquals(listOf("loose"), map[""]?.map(Feed::title))
    }

    @Test
    fun `every source lands somewhere, so an export cannot silently drop one`() {
        val feeds = listOf(
            feed(id = 1, title = "a", tag = "News"),
            feed(id = 2, title = "b", tag = ""),
            feed(id = 3, title = "c", tag = "Tech,News"),
        )
        val map = groupByTag(feeds, listOf("News", "Tech"))
        assertEquals(feeds.map(Feed::title).toSet(), map.values.flatten().map(Feed::title).toSet())
    }
}

/**
 * The list's three narrowing controls and the range gesture.
 *
 * Both are decided by pure functions rather than by the view model precisely
 * so they can be checked here: the bug that prompted them — Select all taking
 * two hundred hidden sources while a search was live — was invisible in the
 * code and obvious the moment it was written down as a fixture.
 */
class SourceNarrowingTest {

    private val bbc = feed(id = 1, title = "BBC", url = "https://bbc.co.uk/rss", tag = "News")
    private val guardian =
        feed(id = 2, title = "Guardian", url = "https://theguardian.com/rss", tag = "News,World")
    private val ars = feed(id = 3, title = "Ars", url = "https://arstechnica.com/feed", tag = "Tech")

    @Test
    fun `nothing set keeps everything`() {
        val all = Narrowing()
        assertTrue(listOf(bbc, guardian, ars).all(all::keeps))
    }

    @Test
    fun `a category keeps only its own sources`() {
        val news = Narrowing(category = "News")
        assertTrue(news.keeps(bbc))
        assertTrue("a source in several categories still counts", news.keeps(guardian))
        assertFalse(news.keeps(ars))
    }

    @Test
    fun `the category is exact where the search is not`() {
        // Searching "New" matches anything containing it; the chip must not,
        // or a chip labelled News would quietly include a source called
        // "Newsnight Tech" filed under Tech.
        val newsnight = feed(id = 4, title = "Newsnight", tag = "Tech")
        assertTrue(newsnight.matches("News"))
        assertFalse(Narrowing(category = "News").keeps(newsnight))
    }

    @Test
    fun `a search inside a category narrows twice`() {
        val both = Narrowing(query = "guardian", category = "News")
        assertFalse(both.keeps(bbc))
        assertTrue(both.keeps(guardian))
    }

    @Test
    fun `the duplicates filter keeps only the ids it was given`() {
        val dupes = Narrowing(duplicatesOnly = true, duplicateIds = setOf(1L, 2L))
        assertTrue(dupes.keeps(bbc))
        assertTrue(dupes.keeps(guardian))
        assertFalse(dupes.keeps(ars))
    }

    @Test
    fun `an armed duplicates filter with no ids keeps nothing`() {
        // The state between arming the filter and the query returning. Keeping
        // everything for that frame would flash the whole list.
        val dupes = Narrowing(duplicatesOnly = true)
        assertFalse(listOf(bbc, guardian, ars).any(dupes::keeps))
    }
}

class SelectionRangeTest {

    private val shown = listOf(10L, 20L, 30L, 40L, 50L)

    @Test
    fun `a range covers both ends`() {
        assertEquals(listOf(20L, 30L, 40L), rangeBetween(shown, anchor = 20L, id = 40L))
    }

    @Test
    fun `dragging upwards is the same range`() {
        assertEquals(listOf(20L, 30L, 40L), rangeBetween(shown, anchor = 40L, id = 20L))
    }

    @Test
    fun `a range of one is the item itself`() {
        assertEquals(listOf(30L), rangeBetween(shown, anchor = 30L, id = 30L))
    }

    @Test
    fun `no anchor means no range`() {
        // The caller falls back to a plain toggle. Extending from nothing has
        // no meaning, and guessing one selects rows nobody pointed at.
        assertTrue(rangeBetween(shown, anchor = null, id = 30L).isEmpty())
    }

    @Test
    fun `an anchor that has been filtered away means no range`() {
        assertTrue(rangeBetween(shown, anchor = 99L, id = 30L).isEmpty())
    }

    @Test
    fun `the run follows the order on screen, not the order of the ids`() {
        // Sorted by name descending, say. The user's finger travels down the
        // list they can see, so that is the list the range is taken from.
        val reversed = listOf(50L, 40L, 30L, 20L, 10L)
        assertEquals(listOf(50L, 40L, 30L), rangeBetween(reversed, anchor = 50L, id = 30L))
    }
}

class ShownSourcesTest {

    @Test
    fun `what select-all takes is the enabled list then the disabled one`() {
        // Not allSources: a search or a category chip filters these two lists
        // and leaves allSources whole, which is how Select all came to take
        // sources that were not on screen.
        val state = SourceListState(
            allSources = listOf(feed(id = 1), feed(id = 2), feed(id = 3)),
            enabledSources = listOf(feed(id = 1)),
            disabledSources = listOf(feed(id = 2)),
        )
        assertEquals(listOf(1L, 2L), state.shownSources.map(Feed::id))
    }
}

/**
 * The category filter does not outlive the category.
 *
 * Recategorising the only source in a category is an ordinary thing to do and
 * it used to empty the screen. The filter went on holding a name nothing
 * carried any more, so every source was excluded; and since the chip row draws
 * the categories that exist, the chip that would have cleared it was gone with
 * the category. An empty list, no stated cause, and no way back except leaving
 * the screen — which threw the view model away and took the filter with it,
 * which is why it looked like a refresh problem.
 */
class CategoryFilterTest {

    @Test
    fun `a category that still exists is kept`() {
        assertEquals("Tech", survivingCategory("Tech", listOf("Misc", "News", "Tech")))
    }

    @Test
    fun `a category that has just been emptied is dropped`() {
        // The exact case: the one feed filed under "Android Development" is
        // moved to "Tech", so the tag stops existing mid-screen.
        assertEquals(null, survivingCategory("Android Development", listOf("Misc", "News", "Tech")))
    }

    @Test
    fun `a rename is the same event from this side`() {
        assertEquals(null, survivingCategory("Tech", listOf("Technology")))
    }

    @Test
    fun `clearing every category clears the filter`() {
        assertEquals(null, survivingCategory("Tech", emptyList()))
    }

    @Test
    fun `no chosen category stays no chosen category`() {
        assertEquals(null, survivingCategory(null, listOf("Misc")))
    }

    @Test
    fun `matching is exact, so a prefix does not keep a dead filter alive`() {
        assertEquals(null, survivingCategory("Tech", listOf("Tech Review")))
    }
}
