package com.saulhdev.feeder

import com.saulhdev.feeder.data.db.models.Feed
import com.saulhdev.feeder.viewmodels.SourceSort
import com.saulhdev.feeder.viewmodels.groupByTag
import com.saulhdev.feeder.viewmodels.matches
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.net.URL
import kotlin.time.Instant

private fun feed(
    id: Long = 1,
    title: String = "",
    url: String = "https://example.com/feed",
    tag: String = "",
    lastSync: Long = 0,
) = Feed(
    id = id,
    title = title,
    url = URL(url),
    tag = tag,
    lastSync = Instant.fromEpochMilliseconds(lastSync),
)

class SourceListTest {

    @Test
    fun `an empty query matches everything`() {
        assertTrue(feed(title = "The Guardian").matches(""))
        assertTrue(feed(title = "The Guardian").matches("   "))
    }

    @Test
    fun `search finds a source by name, address or category`() {
        val f = feed(title = "The Guardian", url = "https://theguardian.com/europe/rss", tag = "News,World")
        assertTrue("by name", f.matches("guardian"))
        assertTrue("by address", f.matches("europe"))
        assertTrue("by category", f.matches("world"))
        assertFalse(f.matches("cricket"))
    }

    @Test
    fun `search ignores case and surrounding space`() {
        val f = feed(title = "Ars Technica")
        assertTrue(f.matches("ARS"))
        assertTrue(f.matches("  ars  "))
    }

    @Test
    fun `sorting by name is case-insensitive`() {
        val feeds = listOf(feed(title = "zdnet"), feed(title = "Ars"), feed(title = "BBC"))
        val sorted = feeds.sortedWith(SourceSort.Title.comparator(emptyMap())).map(Feed::title)
        assertEquals(listOf("Ars", "BBC", "zdnet"), sorted)
    }

    @Test
    fun `sorting by category uses the first of several, not the raw string`() {
        val feeds = listOf(
            feed(title = "b", tag = "World,Alpha"),
            feed(title = "a", tag = "Tech"),
        )
        val sorted = feeds.sortedWith(SourceSort.Category.comparator(emptyMap())).map(Feed::title)
        assertEquals(listOf("a", "b"), sorted)
    }

    @Test
    fun `added reads insertion order off the autogenerated id`() {
        // Ascending, like every comparator here — the view model reverses it
        // when the reader asks for the other direction, so the enum must not
        // bake a direction into itself. "Recently added" used to, which left
        // no way to ask for oldest first and made the menu look like it
        // offered four orders when it offered two and a half.
        val feeds = listOf(
            feed(id = 1, title = "first"),
            feed(id = 7, title = "newest"),
            feed(id = 4, title = "middle"),
        )
        val sorted = feeds.sortedWith(SourceSort.Added.comparator(emptyMap())).map(Feed::title)
        assertEquals(listOf("first", "middle", "newest"), sorted)
    }

    @Test
    fun `every order reverses cleanly`() {
        // What tapping the chosen row does. Worth a test because it is the
        // only way to reach half the orders the menu now offers.
        // Every field distinct, deliberately. A stable sort does not reverse
        // tied elements and should not, so a fixture where all three share a
        // category would be testing Kotlin's sort rather than these
        // comparators.
        val feeds = listOf(
            feed(id = 1, title = "Ars", tag = "Tech"),
            feed(id = 2, title = "zdnet", tag = "World"),
            feed(id = 3, title = "BBC", tag = "News"),
        )
        val latest = mapOf(1L to 300L, 2L to 100L, 3L to 200L)
        SourceSort.entries.forEach { option ->
            val up = feeds.sortedWith(option.comparator(latest)).map(Feed::title)
            val down = feeds.sortedWith(option.comparator(latest).reversed()).map(Feed::title)
            assertEquals(option.name, up, down.reversed())
        }
    }

    @Test
    fun `latest post sorts the quietest feed first`() {
        // The useful end of this order: a feed that has published nothing for
        // months is the one worth looking at.
        val feeds = listOf(
            feed(id = 1, title = "busy"),
            feed(id = 2, title = "quiet"),
            feed(id = 3, title = "middling"),
        )
        val latest = mapOf(1L to 9_000L, 2L to 1_000L, 3L to 5_000L)
        val sorted = feeds.sortedWith(SourceSort.LatestPost.comparator(latest)).map(Feed::title)
        assertEquals(listOf("quiet", "middling", "busy"), sorted)
    }

    @Test
    fun `a feed with no articles at all sorts before every other`() {
        // It is the quietest of the lot, and usually broken, so the top of an
        // ascending list is exactly where it belongs. It must not be dropped
        // or throw for having no entry in the map.
        val feeds = listOf(feed(id = 1, title = "has posts"), feed(id = 2, title = "empty"))
        val latest = mapOf(1L to 5_000L)
        val sorted = feeds.sortedWith(SourceSort.LatestPost.comparator(latest)).map(Feed::title)
        assertEquals(listOf("empty", "has posts"), sorted)
    }

    @Test
    fun `latest post is not last sync`() {
        // The order this replaced sorted on Feeds.lastSync, which records when
        // Whisper last fetched a feed rather than when the feed last published
        // — so a feed checked every hour that has published nothing since
        // March had the most recent value in the list. Nothing here reads
        // lastSync, and this test exists to keep it that way.
        val busyFetchQuietFeed = feed(id = 1, title = "quiet", lastSync = 9_999L)
        val rarelyFetchedLivelyFeed = feed(id = 2, title = "lively", lastSync = 1L)
        val latest = mapOf(1L to 100L, 2L to 8_000L)
        val sorted = listOf(busyFetchQuietFeed, rarelyFetchedLivelyFeed)
            .sortedWith(SourceSort.LatestPost.comparator(latest)).map(Feed::title)
        assertEquals(listOf("quiet", "lively"), sorted)
    }

    @Test
    fun `four orders, and none of them names a direction`() {
        assertEquals(4, SourceSort.entries.size)
    }

    @Test
    fun `every sort option carries a label`() {
        SourceSort.entries.forEach { assertTrue(it.name, it.labelId != 0) }
    }

    @Test
    fun `a stored order resolves by name`() {
        assertEquals(SourceSort.Category, SourceSort.byName("Category"))
        assertEquals(SourceSort.Added, SourceSort.byName("Added"))
    }

    @Test
    fun `an order that no longer exists falls back rather than throwing`() {
        // "LastSync" was a real option and is not any more, so it is sitting in
        // the DataStore of every phone that used it. Resolving by ordinal
        // would have silently repointed those at whatever now occupies that
        // position; resolving by name gives nothing, and nothing means Title.
        assertEquals(SourceSort.Title, SourceSort.byName("LastSync"))
        assertEquals(SourceSort.Title, SourceSort.byName(null))
        assertEquals(SourceSort.Title, SourceSort.byName(""))
    }

    @Test
    fun `grouping by tag puts a multi-category source in every one of them`() {
        val feeds = listOf(
            feed(id = 1, title = "both", tag = "News,Tech"),
            feed(id = 2, title = "tech", tag = "Tech"),
        )
        val map = groupByTag(feeds, listOf("News", "Tech"))
        assertEquals(listOf("both"), map["News"]?.map(Feed::title))
        assertEquals(listOf("both", "tech"), map["Tech"]?.map(Feed::title))
    }

    @Test
    fun `a category is not matched by a prefix of another`() {
        // "New" used to match a source tagged "News", because the tag was one
        // comma-separated string and the check was contains().
        val map = groupByTag(listOf(feed(title = "n", tag = "News")), listOf("New", "News"))
        assertEquals(emptyList<String>(), map["New"]?.map(Feed::title))
        assertEquals(listOf("n"), map["News"]?.map(Feed::title))
    }

    @Test
    fun `the untagged bucket holds only the untagged`() {
        // It once matched every source, so an OPML export wrote each feed
        // twice: once under its category and once under none.
        val feeds = listOf(
            feed(id = 1, title = "filed", tag = "News"),
            feed(id = 2, title = "loose", tag = ""),
        )
        val map = groupByTag(feeds, listOf("News"))
        assertEquals(listOf("loose"), map[""]?.map(Feed::title))
    }

    @Test
    fun `every source lands somewhere, so an export cannot silently drop one`() {
        val feeds = listOf(
            feed(id = 1, title = "a", tag = "News"),
            feed(id = 2, title = "b", tag = ""),
            feed(id = 3, title = "c", tag = "Tech,News"),
        )
        val map = groupByTag(feeds, listOf("News", "Tech"))
        assertEquals(feeds.map(Feed::title).toSet(), map.values.flatten().map(Feed::title).toSet())
    }
}
